In [1]:
from statisco import StockDataFrame

# StockDataFrame
StockDataFrame is a wrapper of yfinance DataFrame, with integrated functionalities to make blazing fast calculations over the data.

In [2]:
msft = StockDataFrame(ticker="MSFT", start="2022-01-01", end="2022-12-31", interval="1d")

In [3]:
msft.calculate(close_returns=True)
msft.calculate(sma=True, interval=3)
msft.calculate(ema=True, interval=3, smooth=2)
msft.calculate(wma=True, interval=3)
msft.calculate(atr=True, interval=3)

In [4]:
msft.head()

,Open,High,Low,Close,Adj Close,Volume,CloseReturns,SMA,EMA,WMA,ATR
Date,,,,,,,,,,,
2022-01-03,335.350006,338.000000,329.779999,334.750000,327.530090,28865100,0.000000,6.944156e-310,6.944156e-310,6.944156e-310,0.000000
2022-01-04,334.829987,335.200012,326.119995,329.010010,321.913910,32674300,-0.017147,1.284112e-316,3.290100e+02,6.944156e-310,0.000000
2022-01-05,325.859985,326.070007,315.980011,316.380005,309.556335,40054300,-0.038388,3.267133e+02,3.163800e+02,3.236517e+02,41.150004
2022-01-06,313.149994,318.700012,311.489990,313.880005,307.110229,39646100,-0.007902,3.197567e+02,3.138800e+02,3.172350e+02,9.773346
2022-01-07,314.149994,316.500000,310.089996,314.040009,307.266815,32720000,0.000510,3.147667e+02,3.140400e+02,3.143767e+02,8.883341

In [5]:
msft.normalize(inplace=True)

In [7]:
msft.head()

,Open,High,Low,Close,Adj Close,Volume,CloseReturns,SMA,EMA,WMA,ATR
Date,,,,,,,,,,,
2022-01-03,1.000000,1.000000,1.000000,1.000000,1.000000,0.242087,0.483968,2.125458e-312,0.000000,0.000000,0.000000
2022-01-04,0.995586,0.976189,0.968543,0.952365,0.951805,0.288983,0.376412,0.000000e+00,1.000000,0.000000,0.000000
2022-01-05,0.919440,0.898546,0.881392,0.847552,0.845760,0.379838,0.243178,1.000000e+00,0.961612,1.000000,1.000000
2022-01-06,0.811545,0.835870,0.842802,0.826805,0.824769,0.374812,0.434403,9.787071e-01,0.954014,0.980174,0.237505
2022-01-07,0.820034,0.817161,0.830769,0.828133,0.826113,0.289545,0.487167,9.634338e-01,0.954500,0.971343,0.215877